#Netskope Checking out something 

name: Howdy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  automating_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build & push Docker image
      run: |
        docker build -t ritman_image .
        docker run ritman_image:latest ls
        
        
        
