#Netskope Checking out something 

name: Howdy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  automating_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
#    - name: Build & push Docker image
#      run: |
#        docker build -t ritm4n/ritman_image .
#        docker run ritman_image:latest 
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Ubuntu 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ritman_Ubu_image:latest

    - name: Build and push CentOS  
      id: docker_build1
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile1
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ritman_Cent_image:latest

    - name: Build and push Alpine 
      id: docker_build2
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile2
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ritman_Alp_image:latest




    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
        
