#Netskope Checking out something 

name: Howdy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  automating_Some_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Testing script
        run: sudo git clone https://github.com/CISOfy/lynis.git
      - name: Running Script
        run: cd lynis && ./lynis audit system -Q
      - name: Finishing
        run: echo "Done ritman"
